### ISSUE TITLE
No link to the webinar 2024

### ISSUE THREAD

**Issue by UlricaZhz** [argonne-lcf/ai-science-training-series#24]
I have already registered and have the account. But have not received any link about the webinar for 2024 from my registered email.

**Comment by ShawnMenz** [comment]
I also encountered the same problem.

**Comment by felker** [comment]
Are you on the Slack workspace? The link is pinned there

**Comment by ShawnMenz** [comment]
Thanks for your reply! I am not in the Slack workspace. Could you please add me into it? The email for Slack account is ***@***.***

Thank you very much!

Zexuan
________________________________
From: Kyle Gerard Felker ***@***.***>
Sent: Tuesday, February 6, 2024 15:19
To: argonne-lcf/ai-science-training-series ***@***.***>
Cc: Meng, Zexuan ***@***.***>; Comment ***@***.***>
Subject: [EXT] Re: [argonne-lcf/ai-science-training-series] No link to the webinar 2024 (Issue #24)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Are you on the Slack workspace? The link is pinned there

**Comment by UlricaZhz** [comment]
I do not in the Slack. My registration email is ***@***.***


------------------ Original ------------------
From: Kyle Gerard Felker ***@***.***&gt;
Date: Tue, Feb 6, 2024 3:19 PM
To: argonne-lcf/ai-science-training-series ***@***.***&gt;
Cc: 人类观察者 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [argonne-lcf/ai-science-training-series] No link to the webinar2024 (Issue #24)





 
Are you on the Slack workspace? The link is pinned there

**Comment by jtchilders** [comment]
I'm sorry but you needed to have registered for this event. Registrations were limited and if you registered, you would receive the appropriate links. Please check your email if you did registere.

**Comment by UlricaZhz** [comment]
I registered it and already have access to machines. Only don't have link&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Taylor Childers ***@***.***&gt;
Date: Tue, Feb 6, 2024 3:24 PM
To: argonne-lcf/ai-science-training-series ***@***.***&gt;
Cc: 人类观察者 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [argonne-lcf/ai-science-training-series] No link to the webinar2024 (Issue #24)





 
I'm sorry but you needed to have registered for this event. Registrations were limited and if you registered, you would receive the appropriate links. Please check your email if you did register.

**Comment by ShawnMenz** [comment]
I registered for this event on Dec 20, 2023, but I still didn't receive any appropriate links till now. Could you please help with this issue? I really appreciate your help!
________________________________
From: Taylor Childers ***@***.***>
Sent: Tuesday, February 6, 2024 15:23
To: argonne-lcf/ai-science-training-series ***@***.***>
Cc: Meng, Zexuan ***@***.***>; Comment ***@***.***>
Subject: [EXT] Re: [argonne-lcf/ai-science-training-series] No link to the webinar 2024 (Issue #24)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I'm sorry but you needed to have registered for this event. Registrations were limited and if you registered, you would receive the appropriate links. Please check your email if you did register.

**Comment by jtchilders** [comment]
Tell me your first/last names that you used for registration. GitHub is not allowing emails.

**Comment by ShawnMenz** [comment]
My first name is Zexuan and my last name is Meng.
________________________________
From: Taylor Childers ***@***.***>
Sent: Tuesday, February 6, 2024 15:35
To: argonne-lcf/ai-science-training-series ***@***.***>
Cc: Meng, Zexuan ***@***.***>; Comment ***@***.***>
Subject: [EXT] Re: [argonne-lcf/ai-science-training-series] No link to the webinar 2024 (Issue #24)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Tell me your first/last names that you used for registration. GitHub is not allowing emails.

**Comment by UlricaZhz** [comment]
> Tell me your first/last names that you used for registration. GitHub is not allowing emails.

Hanzhi Zhang. Thank you for your help!

**Comment by jtchilders** [comment]
Sorry you do not appear on our registration list. Feel free to monitor our Youtube channel as we will post the recording there at a later date.

**Comment by UlricaZhz** [comment]
![IMG_5347](https://github.com/argonne-lcf/ai-science-training-series/assets/34790999/5ccf370f-b050-46ab-bf45-4c6a88c7fa72)
Are all these machines' accesses sent by you? I

**Comment by ShawnMenz** [comment]
Thanks for looking into this concern. I appreciate your help. However, the fact is that I registered for an account for the project named ALCFAITP. I obtained the registration link from the workshop page and I am pretty sure I have registered for the correct project. Here is the confirmation email I received from your organization.

![Screenshot 2024-02-06 155552](https://github.com/argonne-lcf/ai-science-training-series/assets/39453624/b5853588-6925-4e87-ab63-6ee967d2896e)


> Sorry you do not appear on our registration list. Feel free to monitor our Youtube channel as we will post the recording there at a later date.

**Comment by BethanyL** [comment]
Did you register for the training here? https://events.cels.anl.gov/event/436/. That's different than having an ALCF account and requesting to join the project.

**Comment by ShawnMenz** [comment]
> Did you register for the training here? https://events.cels.anl.gov/event/436/. That's different than having an ALCF account and requesting to join the project.

Yes, I registered for the training on this page under the 'registration' tag.

**Comment by UlricaZhz** [comment]
> Did you register for the training here? https://events.cels.anl.gov/event/436/. That's different than having an ALCF account and requesting to join the project.

Yes. The following is the very beginning information I got. I directly clicked REGISTER from this email(now it is closed).

![IMG_5350](https://github.com/argonne-lcf/ai-science-training-series/assets/34790999/262c462b-3696-4c05-8302-6d5d8a754624)

**Comment by UlricaZhz** [comment]
Hi, is thee anyone who can help me to solve this problem?

**Comment by UlricaZhz** [comment]
Hi, as one week last I still have not received any access info to this project, is there anyone who can help me to solve this problem? I am pretty sure I correctly applied to this project as provided evidences during our discussion. I use my university email to apply ALCF account only for this training series. I believe you received my application as I keep receiving update emails for 5 machines. my name is Hanzhi Zhang, and my email domain end with my.unt.edu. I have already missed one workshop last week and seems like to miss the 2nd one now. I really want to participate, could you please check this for me?
